project:
  type: website

website:
  title: "Test2"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Basics"
        contents:
          - index.qmd
      - section: "About"
        contents:
          - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    embed-resources: true
    toc: true



